version: "3.9"

services:
  mysql:
    image: mysql
    container_name: "mysql-api-boleto"

    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lms663
      - MYSQL_DATABASE=api_boleto
      - MYSQL_USER=leandro
      - MYSQL_PASSWORD=lms663
  api:
    build: .
    image: nodejs
    container_name: nodejs-api-boleto
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
